language: python
os: linux
dist: bionic

install:
  - &upgrade_python_toolset pip install --upgrade pip setuptools wheel
  - pip install --upgrade pytest pytest-sugar coverage[toml]>=5.0
  - &install_deps pip install sqlalchemy
  - pip install --upgrade pytest-cov coveralls

_python:
  - &python35
    name: "Python 3.5"
    python: "3.5"
  - &python36
    name: "Python 3.6"
    python: "3.6"
  - &python37
    name: "Python 3.7"
    python: "3.7"
  - &python38
    name: "Python 3.8"
    python: "3.8"
  - &pypy3
    name: "PyPy3"
    python: "pypy3"

_helpers:
  - &build_package python setup.py bdist_wheel clean

  - &static_analysis
    stage: Static analysis
    <<: *python37

  - &code_style_check
    stage: Code style check
    <<: *python37

script:
  - python setup.py develop -v
  - py.test -vv --cov-report= --cov=sqlalchemy_jsonfield test
  - coverage report -m --fail-under 89

jobs:
  include:
    - <<: *static_analysis
      name: "PyLint"
      install:
        - *upgrade_python_toolset
        - *install_deps
        - pip install --upgrade "pylint >= 2.3"
      script:
        - python setup.py --version clean
        - pylint sqlalchemy_jsonfield
    - <<: *static_analysis
      name: "Bandit"
      install:
        - *upgrade_python_toolset
        - pip install --upgrade bandit
      script:
        - bandit -r sqlalchemy_jsonfield
    - <<: *static_analysis
      name: "PEP8"
      install:
        - *upgrade_python_toolset
        - pip install --upgrade flake8 flake8-bugbear
      script:
        - flake8

    - stage: test
      <<: *python35
      after_success:
        - coveralls
    - stage: test
      <<: *python36
      after_success:
        - coveralls
    - stage: test
      <<: *python37
      after_success:
        - coveralls
    - stage: test
      <<: *python38
      after_success:
        - coveralls
    - stage: test
      <<: *pypy3
      after_success:
        - coveralls

    #  - <<: *code_style_check
    #    name: "PEP257"
    #    install:
    #    - *upgrade_python_toolset
    #    - pip install --upgrade pydocstyle
    #    script:
    #    - pydocstyle sqlalchemy_jsonfield

    - stage: deploy
      # This prevents job from appearing in test plan unless commit is tagged:
      if: tag IS present
      # Run on pypy to build not cythonized wheel
      <<: *pypy3
      name: Build universal and cythonized bdist_wheel. Deploy bdist and sdist.
      services: []
      install:
        - *upgrade_python_toolset
        - *install_deps
        - pip install -U --upgrade-strategy=eager --no-cache-dir twine
      before_deploy:
        - pip install -U wheel
      script: *build_package
      deploy:
        - provider: pypi
          # `skip_cleanup: true` is required to preserve binary wheels, built
          skip_cleanup: true
          cleanup: false
          username: penguinolog
          password:
            secure: "d7LUin2jil3ZHyu8W+nXwPpZISSD12/LJVenG1kySvuZ+hV5ovknhKcrEV4IOkyRlGVb/SEbCM60FExGobGn2goAhtv15tTve0KSmDfHbK0YZG7gPwQykFnuS3tOCoo4E4Pxjp17cgmvVuHJDWy546J6w+PGq+hfEL0xFPNR6lZNMd3+HqVnA0XsCbZcuOWFZuDQL4CQIgR1wxgqnD6PMun4P9xBt9C2clJWo6MDy5AaqO0qGodbyIare+c6MPrxluTBnE1ULzGLyn0+lj+V+UP8SyfVfrxp2CokOqs2NbTwuZHrvJu9mOJG3xRTYjyIBrUlWdiTejzDlJ3annqTaxemiFUq6KYLBcHqbugnPtPtqDt47Y9v0DBeJ/OTxZ8B2lFOD4r2IuAcQLkDLvCeESy4SLWDcDcHds6Czj3UIHQ2rB2XgzxYOHz1cpj4ZF84NNYSC0zIEUPXKG8iS2xmnlRHLrgd3jzKct+TaKzuOjN4EHjzea5Yzz6GHySt+EhgABVExste90fp0k7NJ8ipsa+GROMVOzKeYuj+h0djSTRzBxorX32Lisq+X6TXalXTvDup67/IJN9CYmDMPk+yxYqGhhuKUgj19+87dbW2DTCV+5eRxO2J7QMr20cZWLZnLR7tEJl6SPfLITcIBTDh3foa1wQgyJSwLTFoH/wOda4="
          on:
            tags: true
          distributions: sdist bdist_wheel
          upload_docs: false
          skip_existing: true

cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
