sudo: false
language: python
os: linux
python:
- 2.7
- 3.4
- 3.5
- 3.6
- &mainstream_python 3.7-dev
- &pypy pypy
- pypy3.5
install:
- &upgrade_python_toolset pip install --upgrade pip setuptools wheel
- pip install tox-travis
- pip install coveralls
script: tox
after_success:
- coveralls

jobs:
  fast_finish: true
  include:
  - stage: Static analisys
    python: 3.6
    services: []
    install:
    - *upgrade_python_toolset
    - pip install tox
    script:
    - tox -e pylint,bandit
    after_success: skip

  - stage: Code style check
    python: *mainstream_python
    install:
    - *upgrade_python_toolset
    - pip install tox
    script:
    - tox -e pep8,pep257
    after_success: skip

  - stage: deploy
    # This prevents job from appearing in test plan unless commit is tagged:
    if: tag IS present
    # Run on pypy to build not cythonized wheel
    python: *pypy
    services: []
    install:
    - *upgrade_python_toolset
    before_deploy:
    - pip install sqlalchemy
    deploy:
    - provider: pypi
      skip_cleanup: true
      user: penguinolog
      password:
        secure: "d7LUin2jil3ZHyu8W+nXwPpZISSD12/LJVenG1kySvuZ+hV5ovknhKcrEV4IOkyRlGVb/SEbCM60FExGobGn2goAhtv15tTve0KSmDfHbK0YZG7gPwQykFnuS3tOCoo4E4Pxjp17cgmvVuHJDWy546J6w+PGq+hfEL0xFPNR6lZNMd3+HqVnA0XsCbZcuOWFZuDQL4CQIgR1wxgqnD6PMun4P9xBt9C2clJWo6MDy5AaqO0qGodbyIare+c6MPrxluTBnE1ULzGLyn0+lj+V+UP8SyfVfrxp2CokOqs2NbTwuZHrvJu9mOJG3xRTYjyIBrUlWdiTejzDlJ3annqTaxemiFUq6KYLBcHqbugnPtPtqDt47Y9v0DBeJ/OTxZ8B2lFOD4r2IuAcQLkDLvCeESy4SLWDcDcHds6Czj3UIHQ2rB2XgzxYOHz1cpj4ZF84NNYSC0zIEUPXKG8iS2xmnlRHLrgd3jzKct+TaKzuOjN4EHjzea5Yzz6GHySt+EhgABVExste90fp0k7NJ8ipsa+GROMVOzKeYuj+h0djSTRzBxorX32Lisq+X6TXalXTvDup67/IJN9CYmDMPk+yxYqGhhuKUgj19+87dbW2DTCV+5eRxO2J7QMr20cZWLZnLR7tEJl6SPfLITcIBTDh3foa1wQgyJSwLTFoH/wOda4="
      on:
        tags: true
        distributions: sdist bdist_wheel
      skip_upload_docs: true

cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
